#!/usr/bin/env bash
set -euo pipefail

# Ensure that docker is installed:
if ! which docker >/dev/null
then
  echo 'this script requires docker'
  exit 1
fi

# Ensure that docker-compose is installed:
if ! which docker-compose >/dev/null
then
  echo 'this script requires docker-compose'
  exit 1
fi

# Ensure that we can connect to Docker:
ERRS="$(docker info --format '{{range .ServerErrors}}{{.}}{{end}}' 2>&1)"
if ! test -z "$ERRS"
then
  echo 'cannot connect to docker:'
  echo "$ERRS"
  exit 1
fi

# Start setup; cd into the path of this script:
if test -z "${BASH_SOURCE[0]:-}"
then
  echo 'failed to find script path'
  exit 1
fi
pushd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null

# Take down any existing services:
echo 'Taking down any existing services...'
docker-compose down --remove-orphans --volumes --timeout 5 --rmi local

# Ensure that port 80 is not in use;
if lsof -iTCP:80 -sTCP:LISTEN >/dev/null 2>/dev/null
then
  echo 'Cannot start: port 80 is already in use'
  exit 1
fi

# Pull images, create containers, and start:
# (This is basically the same as docker-compose up)
echo 'Pulling latest versions of images...'
docker-compose pull
echo 'Creating containers...'
docker-compose create --pull never --no-build
echo 'Starting containers...'
docker-compose start

# Wait for MongoDB to start:
echo "Waiting for MongoDB to start:"
while ! docker-compose exec mongo mongo --eval ";" >/dev/null 2>/dev/null
do
  sleep 1
done

# Set up MongoDB replica set:
echo "Initializing mongodb as replica set..."
docker-compose exec mongo mongo matchminer --quiet --eval "rs.initiate();"

# Load demo data into MongoDB:
echo "Loading demo data into mongo..."
rm -rf ./matchminer
tar -xzvf matchminer.tar.gz
docker-compose cp matchminer mongo:/
rm -rf ./matchminer
docker-compose exec mongo mongorestore --quiet matchminer

# Setup complete!
popd >/dev/null

# Wait for MatchMiner UI to be ready:
echo "Waiting for MatchMiner UI to be ready..."
while ! nc -z localhost 80
do
  sleep 1
done

# Notify user:
echo "SUCCESS. To view, navigate to http://localhost"
